### ISSUE TITLE
Issue with Usernames

### ISSUE THREAD

**Issue by SK83RJOSH** [FabricLabs/soundtrack#29]
When a User's username contains special characters or non-UTF8 characters their profile cannot be viewed.

For instance the User "{-_-}" cannot be viewed at http://soundtrack.io/{-_-} because it is infact an invalid URL. So there needs to be a fallback inplace when a username contains special characters, or this should be disallowed completely.

**Comment by martindale** [comment]
Test with: https://chat.fabric.pub/#/room/#soundtrack:fabric.pub
